
server:
  port: 8081

info:
  app:
    name: CRUD Demo App
    version: 1.0.0

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456789
